### ISSUE TITLE
很潮喔！

### ISSUE THREAD

**Issue by thekdesign** [EastSun5566/let-it-go#1]

**Comment by EastSun5566** [comment]
沒你潮吧～

**Comment by EastSun5566** [comment]
@thekdesign 來用用看新版 Demo: https://eastsun5566.github.io/let-it-go/
不錯 der 話幫我 close issue

**Comment by thekdesign** [comment]
@EastSun5566 我覺得你的「**ALPHA RANGE**」只有 0 跟 1 不夠潮，最理想是可以潮到天翻地覆，令人望塵莫及。

**Comment by EastSun5566** [comment]
@thekdesign 靠背歐，透明度是要怎麼超過 0 到 1 啦乾

**Comment by thekdesign** [comment]
> @thekdesign 靠背歐，透明度是要怎麼超過 0 到 1 啦乾，確實不夠潮

有沒有 0.5 可以調

**Comment by EastSun5566** [comment]
> > @thekdesign 靠背歐，透明度是要怎麼超過 0 到 1 啦乾，確實不夠潮
> 
> 有沒有 0.5 可以調

對齁，好像不是 1 就是 0，我來改，感謝回饋

**Comment by EastSun5566** [comment]
@thekdesign 更新啦～～～ https://eastsun5566.github.io/let-it-go/

**Comment by thekdesign** [comment]
太神啦
